{{- range .Values.configmaps }}
{{ $configmaps := . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmaps.name }}
  namespace: ms-{{ $.Values.global.app_name }}
  labels:
    managed-by: "kubeapps"
    {{- range $key, $value := $configmaps.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    {{- range $key, $value := $configmaps.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- with $configmaps.data }}
data:
  {{- toYaml . | nindent 4 -}}
{{- end }}
{{- end }}
