{{- range .Values.cronjobs }}
{{- $cronjob := . }}
{{- if $cronjob.enabled }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $.Values.global.app_name }}-cronjob-{{ $cronjob.name }}
  namespace: ms-{{ $.Values.global.app_name }}
  labels:
    app: {{ $.Values.global.app_name }}
    managed-by: "kubeapps"
spec:
  {{- if (hasKey $.Values.global.cronjob "historylimit") }}
  failedJobsHistoryLimit: {{ $.Values.global.cronjob.historylimit.failed }}
  successfulJobsHistoryLimit: {{ $.Values.global.cronjob.historylimit.successful }}
  {{- else if (hasKey $cronjob "historylimit") }}
  failedJobsHistoryLimit: {{ $cronjob.historylimit.failed }}
  successfulJobsHistoryLimit: {{ $cronjob.historylimit.successful }}
  {{- else }}
  failedJobsHistoryLimit: 0
  successfulJobsHistoryLimit: 0
  {{- end }}
  concurrencyPolicy: Forbid
  schedule: {{ $cronjob.schedule | quote }}
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ $cronjob.ttl | default 3600 }}
      parallelism: {{ $cronjob.parallelism | default 1 }}
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          {{- with $cronjob.serviceaccount }}
          serviceAccountName: {{ $cronjob.serviceaccount }}
          {{- end }}
          restartPolicy: OnFailure
          containers:
          - name: {{ $.Values.global.app_name }}-cronjob-{{ $cronjob.name }}
            {{- if not $cronjob.tag }}
            image: {{ $cronjob.image }}:{{ $.Values.global.image.tag }}
            {{- else }}
            image: {{ $cronjob.image }}:{{ $cronjob.tag }}
            {{- end }}
            {{- if $cronjob.command }}
            command: [ {{ $cronjob.command | quote }} ]
            {{- end }}
            {{- if $cronjob.args }}
            {{- if eq (kindOf $cronjob.args) "slice" }}
            args: {{ toJson $cronjob.args}}
            {{- end }}
            {{- if eq (kindOf $cronjob.args) "string" }}
            args: [ {{ $cronjob.args | quote }} ]
            {{- end }}
            {{- end }}
            env:
            - name: APP_NAME
              value: {{ $.Values.global.app_name }}
            - name: APP_STAGE
              value: {{ $.Values.global.app_stage }}
            {{- if $cronjob.env }}{{ toYaml $cronjob.env | nindent 12}}{{- end }}
            {{- if $cronjob.envFrom }}
            envFrom: {{ toYaml $cronjob.envFrom | nindent 12}}
            {{- end }}
            resources:
              limits:
                cpu: {{ $cronjob.cpu }}
                memory: {{ $cronjob.memory }}
              requests:
                cpu: {{ $cronjob.cpu }}
                memory: {{ $cronjob.memory }}
{{- end }}
{{- end }}
