{{- if $.Values.global.metrics.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ .Values.global.app_name }}-metrics
    monitor: prometheus
    managed-by: "kubeapps"
  name: {{ .Values.global.app_name }}-metrics-service-monitor
spec:
  endpoints:
  - path: /metrics
    port: exporter
  selector:
    matchLabels:
      metrics: enabled
      app: {{ .Values.global.app_name }}-metrics
{{- end }}
