{{- if $.Values.global.jvm_metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.global.app_name }}-service-jvm-metrics
  namespace: ms-{{ $.Values.global.app_name }}
  labels:
    app: {{ $.Values.global.app_name }}-jvm-metrics
    jvm-metrics: enabled
    managed-by: "kubeapps"
spec:
  ports:
  - port: {{ $.Values.global.jvm_metrics.port }}
    protocol: TCP
    targetPort: {{ $.Values.global.jvm_metrics.port }}
    name: exporter
  selector:
    jvm-metrics: enabled
    namespace: ms-{{ $.Values.global.app_name }}
  type: {{ default "ClusterIP" $.Values.global.jvm_metrics.type }}
{{- end }}
