{{- if $.Values.global.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.global.app_name }}-service-metrics
  namespace: ms-{{ $.Values.global.app_name }}
  labels:
    app: {{ $.Values.global.app_name }}-metrics
    metrics: enabled
    managed-by: "kubeapps"
spec:
  ports:
  - port: {{ $.Values.global.metrics.port }}
    protocol: TCP
    targetPort: {{ $.Values.global.metrics.port }}
    name: exporter
  selector:
    metrics: enabled
    namespace: ms-{{ $.Values.global.app_name }}
  type: {{ default "ClusterIP" $.Values.global.metrics.type }}
{{- end }}
