global:
  app_stage: dev
  jvm_metrics:
    enabled: true
    port: 8080
  image:
    tag: "*** INFORME UMA TAG ***"

picpay-ms:
  apis:
    - name: api
      args: "java -Xms450m -Xmx450m -XX:MaxRAM=800m -javaagent:/newrelic/newrelic.jar -jar /app.jar"
      envFrom:
        - secretRef:
            name: envs
      health:
        path: /health
      readiness:
        initialDelaySeconds: 30
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 10
        timeoutSeconds: 5
      liveness:
        initialDelaySeconds: 300
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 10
        timeoutSeconds: 5
      containerPort: 8803
      image:
        repositoryURI: 289208114389.dkr.ecr.us-east-1.amazonaws.com/picpay-dev/card-pre-consumer
      ingress:
        - enabled: true
          type: internal-microservices
          hosts:
            - hostname: card-pre-consumer.ms.dev
            - hostname: dev.card-pre-consumer.service.picpay.local
      limits_memory: 900Mi
      limits_cpu: 1000m
      requests_cpu: 100m
      requests_memory: 900Mi
      service:
        enabled: true
        port: 80
        targetPort: 8803

  workers:
    - name: card-pre-consumer-worker
      args: "java  -XX:PermSize=80m -XX:MaxPermSize=150m -Xms300m -Xmx300m -XX:MaxRAM=400m -javaagent:/newrelic/newrelic.jar -cp /app.jar -javaagent:/jmx_exporter/jmx_prometheus_javaagent-0.14.0.jar=8080:/jmx_exporter/config.yml -Dloader.main=com.picpay.cardpreconsumer.CardPreConsumerWorkerApplication org.springframework.boot.loader.PropertiesLauncher"
      enabled: true
      image: 289208114389.dkr.ecr.us-east-1.amazonaws.com/picpay-dev/card-pre-consumer
      limits_memory: 600Mi
      limits_cpu: 200m
      requests_cpu: 10m
      requests_memory: 400Mi
      envFrom:
        - secretRef:
            name: envs